### PR TITLE
Add apis.infinitude.me.uk to CORS List

### PR DESCRIPTION
**Pull request by InfinitudeUK**
Add cloud.infinitude.me.uk to CORS List for easier integration into Infinitude site.

### CODE REVIEW

**Comment by InfinitudeUK** [comment]
I signed it

**Comment by lgarron** [comment]
I can't reach `https://apis.infinitude.me.uk/`;  will there be a client-side website there soon?

**Comment by InfinitudeUK** [comment]
Yes.

**Comment by InfinitudeUK** [comment]
I have created simple HSTS domain checker on https://apis.infinitude.me.uk for testing. https://apis.infinitude.me.uk/hsts.html

**Comment by lgarron** [comment]
Hmm, did you want `apis.` or `cloud.`? The final state of the PR actually had `cloud.`

**Comment by InfinitudeUK** [comment]
When I created the pull request. I included apis.infinitude.me.uk but then I later changed it to cloud.infinitude.me.uk. So the final state is right. I thought about adding both but I don't need the extra subdomains on the CORS list.

**Comment by InfinitudeUK** [comment]
Thank you for adding the subdomain to the CORS List. If you even need to test it. You can access it from here https://cloud.infinitude.me.uk/hsts.html.

**Comment by lgarron** [comment]
> You can access it from here https://cloud.infinitude.me.uk/hsts.html.

Seems to work! Just keep in mind that the API may still change without notice (although I hope to give advance warning if this happens).

Good luck with your projects. :-)

**Pull request merged**
