### PR TITLE
Add look-at-my.site to CORS whitelist

### PR DESCRIPTION
**Pull request by xinan**
Hi, 

I am creating a little app what checks HTTP(S) headers and suggest potential security loopholes for websites. It is at `look-at-my.site`. It is still work-in-progress at the moment, populated with mocks. I would like to add it to the whitelist so that I can use the API for part of my checks. 

Thanks!

### CODE REVIEW

**Comment by xinan** [comment]
I signed it!

**Comment by lgarron** [comment]
Thanks for the PR!

Could you give a quick explanation of why your site needs to access the API client-side?

**Comment by xinan** [comment]
One of the checks that our site would like to provide is checking whether a site has HSTS header set, and whether it is in the chrome hardcoded list. If not, we will advice the site owner to do so.

**Comment by lgarron** [comment]
> One of the checks that our site would like to provide is checking whether a site has HSTS header set, and whether it is in the chrome hardcoded list. If not, we will advice the site owner to do so.

Right, in order to check if the HSTS header is set, you'll need to connect from another server (or at least a non-browser client). Is it possible to use the hstspreload API from that server, too?

**Comment by xinan** [comment]
I was actually thinking of using the hstspreload API to check the header. Now we have plans to implement more advanced checks. So I guess we will use a server for that. This PR could be discarded. Thanks!

**Comment by lgarron** [comment]
> Now we have plans to implement more advanced checks. So I guess we will use a server for that. This PR could be discarded. Thanks!

Alright, good luck!

**Pull request closed without merging**
